const fullCountryInfo = [
  { fullName: 'Afghanistan', alpha2: 'AF', alpha3: 'AFG', unCode: '004' },
  { fullName: 'ALA Aland Islands', alpha2: 'AX', alpha3: 'ALA', unCode: '248' },
  { fullName: 'Albania', alpha2: 'AL', alpha3: 'ALB', unCode: '008' },
  { fullName: 'Algeria', alpha2: 'DZ', alpha3: 'DZA', unCode: '012' },
  { fullName: 'American Samoa', alpha2: 'AS', alpha3: 'ASM', unCode: '016' },
  { fullName: 'Andorra', alpha2: 'AD', alpha3: 'AND', unCode: '020' },
  { fullName: 'Angola', alpha2: 'AO', alpha3: 'AGO', unCode: '024' },
  { fullName: 'Anguilla', alpha2: 'AI', alpha3: 'AIA', unCode: '660' },
  { fullName: 'Antarctica', alpha2: 'AQ', alpha3: 'ATA', unCode: '010' },
  { fullName: 'Antigua and Barbuda', alpha2: 'AG', alpha3: 'ATG', unCode: '028' },
  { fullName: 'Argentina', alpha2: 'AR', alpha3: 'ARG', unCode: '032' },
  { fullName: 'Armenia', alpha2: 'AM', alpha3: 'ARM', unCode: '051' },
  { fullName: 'Aruba', alpha2: 'AW', alpha3: 'ABW', unCode: '533' },
  { fullName: 'Australia', alpha2: 'AU', alpha3: 'AUS', unCode: '036' },
  { fullName: 'Austria', alpha2: 'AT', alpha3: 'AUT', unCode: '040' },
  { fullName: 'Azerbaijan', alpha2: 'AZ', alpha3: 'AZE', unCode: '031' },
  //
  { fullName: 'Bahamas', alpha2: 'BS', alpha3: 'BHS', unCode: '044' },
  { fullName: 'Bahrain', alpha2: 'BH', alpha3: 'BHR', unCode: '048' },
  { fullName: 'Bangladesh', alpha2: 'BD', alpha3: 'BGD', unCode: '050' },
  { fullName: 'Barbados', alpha2: 'BB', alpha3: 'BRB', unCode: '052' },
  { fullName: 'Belarus', alpha2: 'BY', alpha3: 'BLR', unCode: '112' },
  { fullName: 'Belgium', alpha2: 'BE', alpha3: 'BEL', unCode: '056' },
  { fullName: 'Belize', alpha2: 'BZ', alpha3: 'BLZ', unCode: '084' },
  { fullName: 'Benin', alpha2: 'BJ', alpha3: 'BEN', unCode: '204' },
  { fullName: 'Bermuda', alpha2: 'BM', alpha3: 'BMU', unCode: '060' },
  { fullName: 'Bhutan', alpha2: 'BT', alpha3: 'BTN', unCode: '064' },
  { fullName: 'Bolivia', alpha2: 'BO', alpha3: 'BOL', unCode: '068' },
  { fullName: 'Bosnia and Herzegovina', alpha2: 'BA', alpha3: 'BIH', unCode: '070' },
  { fullName: 'Botswana', alpha2: 'BW', alpha3: 'BWA', unCode: '072' },
  { fullName: 'Bouvet Island', alpha2: 'BV', alpha3: 'BVT', unCode: '074' },
  { fullName: 'Brazil', alpha2: 'BR', alpha3: 'BRA', unCode: '076' },
  { fullName: 'British Virgin Islands', alpha2: 'VG', alpha3: 'VGB', unCode: '092' },
  { fullName: 'British Indian Ocean Territory', alpha2: 'IO', alpha3: 'IOT', unCode: '086' },
  { fullName: 'Brunei Darussalam', alpha2: 'BN', alpha3: 'BRN', unCode: '096' },
  { fullName: 'Bulgaria', alpha2: 'BG', alpha3: 'BGR', unCode: '100' },
  { fullName: 'Burkina Faso', alpha2: 'BF', alpha3: 'BFA', unCode: '854' },
  { fullName: 'Burundi', alpha2: 'BI', alpha3: 'BDI', unCode: '108' },
  // C
  { fullName: 'Cambodia', alpha2: 'KH', alpha3: 'KHM', unCode: '116' },
  { fullName: 'Cameroon', alpha2: 'CM', alpha3: 'CMR', unCode: '120' },
  { fullName: 'Canada', alpha2: 'CA', alpha3: 'CAN', unCode: '124' },
  { fullName: 'Cape Verde', alpha2: 'CV', alpha3: 'CPV', unCode: '132' },
  { fullName: 'Cayman Islands', alpha2: 'KY', alpha3: 'CYM', unCode: '136' },
  { fullName: 'Central African Republic', alpha2: 'CF', alpha3: 'CAF', unCode: '140' },
  { fullName: 'Chad', alpha2: 'TD', alpha3: 'TCD', unCode: '148' },
  { fullName: 'Chile', alpha2: 'CL', alpha3: 'CHL', unCode: '152' },
  { fullName: 'China', alpha2: 'CN', alpha3: 'CHN', unCode: '156' },
  { fullName: 'Hong Kong, SAR China', alpha2: 'HK', alpha3: 'HKG', unCode: '344' },
  { fullName: 'Macao, SAR China', alpha2: 'MO', alpha3: 'MAC', unCode: '446' },
  { fullName: 'Christmas Island', alpha2: 'CX', alpha3: 'CXR', unCode: '162' },
  { fullName: 'Cocos(Keeling) Islands', alpha2: 'CC', alpha3: 'CCK', unCode: '166' },
  { fullName: 'Colombia', alpha2: 'CO', alpha3: 'COL', unCode: '170' },
  { fullName: 'Comoros', alpha2: 'KM', alpha3: 'COM', unCode: '174' },
  { fullName: 'Congo(Brazzaville)', alpha2: 'CG', alpha3: 'COG', unCode: '178' },
  { fullName: 'Congo, (Kinshasa)', alpha2: 'CD', alpha3: 'COD', unCode: '180' },
  { fullName: 'Cook Islands', alpha2: 'CK', alpha3: 'COK', unCode: '184' },
  { fullName: 'Costa Rica', alpha2: 'CR', alpha3: 'CRI', unCode: '188' },
  { fullName: "Côte d'Ivoire", alpha2: 'CI', alpha3: 'CIV', unCode: '384' },
  { fullName: 'Croatia', alpha2: 'HR', alpha3: 'HRV', unCode: '191' },
  { fullName: 'Cuba', alpha2: 'CU', alpha3: 'CUB', unCode: '192' },
  { fullName: 'Cyprus', alpha2: 'CY', alpha3: 'CYP', unCode: '196' },
  { fullName: 'Czech Republic', alpha2: 'CZ', alpha3: 'CZE', unCode: '203' },

  // D
  { fullName: 'Denmark', alpha2: 'DK', alpha3: 'DNK', unCode: '208' },
  { fullName: 'Djibouti', alpha2: 'DJ', alpha3: 'DJI', unCode: '262' },
  { fullName: 'Dominica', alpha2: 'DM', alpha3: 'DMA', unCode: '212' },
  { fullName: 'Dominican Republic', alpha2: 'DO', alpha3: 'DOM', unCode: '214' },

  // E
  { fullName: 'Ecuador', alpha2: 'EC', alpha3: 'ECU', unCode: '218' },
  { fullName: 'Egypt', alpha2: 'EG', alpha3: 'EGY', unCode: '818' },
  { fullName: 'El Salvador', alpha2: 'SV', alpha3: 'SLV', unCode: '222' },
  { fullName: 'Equatorial Guinea', alpha2: 'GQ', alpha3: 'GNQ', unCode: '226' },
  { fullName: 'Eritrea', alpha2: 'ER', alpha3: 'ERI', unCode: '232' },
  { fullName: 'Estonia', alpha2: 'EE', alpha3: 'EST', unCode: '233' },
  { fullName: 'Ethiopia', alpha2: 'ET', alpha3: 'ETH', unCode: '231' },

  // F
  { fullName: 'Falkland Islands(Malvinas)', alpha2: 'FK', alpha3: 'FLK', unCode: '238' },
  { fullName: 'Faroe Islands', alpha2: 'FO', alpha3: 'FRO', unCode: '234' },
  { fullName: 'Fiji', alpha2: 'FJ', alpha3: 'FJI', unCode: '242' },
  { fullName: 'Finland', alpha2: 'FI', alpha3: 'FIN', unCode: '246' },
  { fullName: 'France', alpha2: 'FR', alpha3: 'FRA', unCode: '250' },
  { fullName: 'French Guiana', alpha2: 'GF', alpha3: 'GUF', unCode: '254' },
  { fullName: 'French Polynesia', alpha2: 'PF', alpha3: 'PYF', unCode: '258' },
  { fullName: 'French Southern Territories', alpha2: 'TF', alpha3: 'ATF', unCode: '260' },

  // G
  { fullName: 'Gabon', alpha2: 'GA', alpha3: 'GAB', unCode: '266' },
  { fullName: 'Gambia', alpha2: 'GM', alpha3: 'GMB', unCode: '270' },
  { fullName: 'Georgia', alpha2: 'GE', alpha3: 'GEO', unCode: '268' },
  { fullName: 'Germany', alpha2: 'DE', alpha3: 'DEU', unCode: '276' },
  { fullName: 'Ghana', alpha2: 'GH', alpha3: 'GHA', unCode: '288' },
  { fullName: 'Gibraltar', alpha2: 'GI', alpha3: 'GIB', unCode: '292' },
  { fullName: 'Greece', alpha2: 'GR', alpha3: 'GRC', unCode: '300' },
  { fullName: 'Greenland', alpha2: 'GL', alpha3: 'GRL', unCode: '304' },
  { fullName: 'Grenada', alpha2: 'GD', alpha3: 'GRD', unCode: '308' },
  { fullName: 'Guadeloupe', alpha2: 'GP', alpha3: 'GLP', unCode: '312' },
  { fullName: 'Guam', alpha2: 'GU', alpha3: 'GUM', unCode: '316' },
  { fullName: 'Guatemala', alpha2: 'GT', alpha3: 'GTM', unCode: '320' },
  { fullName: 'Guernsey', alpha2: 'GG', alpha3: 'GGY', unCode: '831' },
  { fullName: 'Guinea', alpha2: 'GN', alpha3: 'GIN', unCode: '324' },
  { fullName: 'Guinea - Bissau', alpha2: 'GW', alpha3: 'GNB', unCode: '624' },
  { fullName: 'Guyana', alpha2: 'GY', alpha3: 'GUY', unCode: '328' },

  // H
  { fullName: 'Haiti', alpha2: 'HT', alpha3: 'HTI', unCode: '332' },
  { fullName: 'Heard and Mcdonald Islands', alpha2: 'HM', alpha3: 'HMD', unCode: '334' },
  { fullName: 'Holy See(Vatican City State)', alpha2: 'VA', alpha3: 'VAT', unCode: '336' },
  { fullName: 'Honduras', alpha2: 'HN', alpha3: 'HND', unCode: '340' },
  { fullName: 'Hungary', alpha2: 'HU', alpha3: 'HUN', unCode: '348' },
  { fullName: 'Iceland', alpha2: 'IS', alpha3: 'ISL', unCode: '352' },

  // I
  { fullName: 'India', alpha2: 'IN', alpha3: 'IND', unCode: '356' },
  { fullName: 'Indonesia', alpha2: 'ID', alpha3: 'IDN', unCode: '360' },
  { fullName: 'Iran, Islamic Republic of', alpha2: 'IR', alpha3: 'IRN', unCode: '364' },
  { fullName: 'Iraq', alpha2: 'IQ', alpha3: 'IRQ', unCode: '368' },
  { fullName: 'Ireland', alpha2: 'IE', alpha3: 'IRL', unCode: '372' },
  { fullName: 'Isle of Man', alpha2: 'IM', alpha3: 'IMN', unCode: '833' },
  { fullName: 'Israel', alpha2: 'IL', alpha3: 'ISR', unCode: '376' },
  { fullName: 'Italy', alpha2: 'IT', alpha3: 'ITA', unCode: '380' },

  // J
  { fullName: 'Jamaica', alpha2: 'JM', alpha3: 'JAM', unCode: '388' },
  { fullName: 'Japan', alpha2: 'JP', alpha3: 'JPN', unCode: '392' },
  { fullName: 'Jersey', alpha2: 'JE', alpha3: 'JEY', unCode: '832' },
  { fullName: 'Jordan', alpha2: 'JO', alpha3: 'JOR', unCode: '400' },

  // K
  { fullName: 'Kazakhstan', alpha2: 'KZ', alpha3: 'KAZ', unCode: '398' },
  { fullName: 'Kenya', alpha2: 'KE', alpha3: 'KEN', unCode: '404' },
  { fullName: 'Kiribati', alpha2: 'KI', alpha3: 'KIR', unCode: '296' },
  { fullName: 'Korea(North)', alpha2: 'KP', alpha3: 'PRK', unCode: '408' },
  { fullName: 'Korea(South)', alpha2: 'KR', alpha3: 'KOR', unCode: '410' },
  { fullName: 'Kuwait', alpha2: 'KW', alpha3: 'KWT', unCode: '414' },
  { fullName: 'Kyrgyzstan', alpha2: 'KG', alpha3: 'KGZ', unCode: '417' },

  // L
  { fullName: 'Lao PDR', alpha2: 'LA', alpha3: 'LAO', unCode: '418' },
  { fullName: 'Latvia', alpha2: 'LV', alpha3: 'LVA', unCode: '428' },
  { fullName: 'Lebanon', alpha2: 'LB', alpha3: 'LBN', unCode: '422' },
  { fullName: 'Lesotho', alpha2: 'LS', alpha3: 'LSO', unCode: '426' },
  { fullName: 'Liberia', alpha2: 'LR', alpha3: 'LBR', unCode: '430' },
  { fullName: 'Libya', alpha2: 'LY', alpha3: 'LBY', unCode: '434' },
  { fullName: 'Liechtenstein', alpha2: 'LI', alpha3: 'LIE', unCode: '438' },
  { fullName: 'Lithuania', alpha2: 'LT', alpha3: 'LTU', unCode: '440' },
  { fullName: 'Luxembourg', alpha2: 'LU', alpha3: 'LUX', unCode: '442' },

  // M
  { fullName: 'Macedonia, Republic of', alpha2: 'MK', alpha3: 'MKD', unCode: '807' },
  { fullName: 'Madagascar', alpha2: 'MG', alpha3: 'MDG', unCode: '450' },
  { fullName: 'Malawi', alpha2: 'MW', alpha3: 'MWI', unCode: '454' },
  { fullName: 'Malaysia', alpha2: 'MY', alpha3: 'MYS', unCode: '458' },
  { fullName: 'Maldives', alpha2: 'MV', alpha3: 'MDV', unCode: '462' },
  { fullName: 'Mali', alpha2: 'ML', alpha3: 'MLI', unCode: '466' },
  { fullName: 'Malta', alpha2: 'MT', alpha3: 'MLT', unCode: '470' },
  { fullName: 'Marshall Islands', alpha2: 'MH', alpha3: 'MHL', unCode: '584' },
  { fullName: 'Martinique', alpha2: 'MQ', alpha3: 'MTQ', unCode: '474' },
  { fullName: 'Mauritania', alpha2: 'MR', alpha3: 'MRT', unCode: '478' },
  { fullName: 'Mauritius', alpha2: 'MU', alpha3: 'MUS', unCode: '480' },
  { fullName: 'Mayotte', alpha2: 'YT', alpha3: 'MYT', unCode: '175' },
  { fullName: 'Mexico', alpha2: 'MX', alpha3: 'MEX', unCode: '484' },
  { fullName: 'Micronesia, Federated States of', alpha2: 'FM', alpha3: 'FSM', unCode: '583' },
  { fullName: 'Moldova', alpha2: 'MD', alpha3: 'MDA', unCode: '498' },
  { fullName: 'Monaco', alpha2: 'MC', alpha3: 'MCO', unCode: '492' },
  { fullName: 'Mongolia', alpha2: 'MN', alpha3: 'MNG', unCode: '496' },
  { fullName: 'Montenegro', alpha2: 'ME', alpha3: 'MNE', unCode: '499' },
  { fullName: 'Montserrat', alpha2: 'MS', alpha3: 'MSR', unCode: '500' },
  { fullName: 'Morocco', alpha2: 'MA', alpha3: 'MAR', unCode: '504' },
  { fullName: 'Mozambique', alpha2: 'MZ', alpha3: 'MOZ', unCode: '508' },
  { fullName: 'Myanmar', alpha2: 'MM', alpha3: 'MMR', unCode: '104' },

  // N
  { fullName: 'Namibia', alpha2: 'NA', alpha3: 'NAM', unCode: '516' },
  { fullName: 'Nauru', alpha2: 'NR', alpha3: 'NRU', unCode: '520' },
  { fullName: 'Nepal', alpha2: 'NP', alpha3: 'NPL', unCode: '524' },
  { fullName: 'Netherlands', alpha2: 'NL', alpha3: 'NLD', unCode: '528' },
  { fullName: 'Netherlands Antilles', alpha2: 'AN', alpha3: 'ANT', unCode: '530' },
  { fullName: 'New Caledonia', alpha2: 'NC', alpha3: 'NCL', unCode: '540' },
  { fullName: 'New Zealand', alpha2: 'NZ', alpha3: 'NZL', unCode: '554' },
  { fullName: 'Nicaragua', alpha2: 'NI', alpha3: 'NIC', unCode: '558' },
  { fullName: 'Niger', alpha2: 'NE', alpha3: 'NER', unCode: '562' },
  { fullName: 'Nigeria', alpha2: 'NG', alpha3: 'NGA', unCode: '566' },
  { fullName: 'Niue', alpha2: 'NU', alpha3: 'NIU', unCode: '570' },
  { fullName: 'Norfolk Island', alpha2: 'NF', alpha3: 'NFK', unCode: '574' },
  { fullName: 'Northern Mariana Islands', alpha2: 'MP', alpha3: 'MNP', unCode: '580' },
  { fullName: 'Norway', alpha2: 'NO', alpha3: 'NOR', unCode: '578' },

  // O
  { fullName: 'Oman', alpha2: 'OM', alpha3: 'OMN', unCode: '512' },

  // P
  { fullName: 'Pakistan', alpha2: 'PK', alpha3: 'PAK', unCode: '586' },
  { fullName: 'Palau', alpha2: 'PW', alpha3: 'PLW', unCode: '585' },
  { fullName: 'Palestinian Territory', alpha2: 'PS', alpha3: 'PSE', unCode: '275' },
  { fullName: 'Panama', alpha2: 'PA', alpha3: 'PAN', unCode: '591' },
  { fullName: 'Papua New Guinea', alpha2: 'PG', alpha3: 'PNG', unCode: '598' },
  { fullName: 'Paraguay', alpha2: 'PY', alpha3: 'PRY', unCode: '600' },
  { fullName: 'Peru', alpha2: 'PE', alpha3: 'PER', unCode: '604' },
  { fullName: 'Philippines', alpha2: 'PH', alpha3: 'PHL', unCode: '608' },
  { fullName: 'Pitcairn', alpha2: 'PN', alpha3: 'PCN', unCode: '612' },
  { fullName: 'Poland', alpha2: 'PL', alpha3: 'POL', unCode: '616' },
  { fullName: 'Portugal', alpha2: 'PT', alpha3: 'PRT', unCode: '620' },
  { fullName: 'Puerto Rico', alpha2: 'PR', alpha3: 'PRI', unCode: '630' },

  // Q
  { fullName: 'Qatar', alpha2: 'QA', alpha3: 'QAT', unCode: '634' },

  // R
  { fullName: 'Réunion', alpha2: 'RE', alpha3: 'REU', unCode: '638' },
  { fullName: 'Romania', alpha2: 'RO', alpha3: 'ROU', unCode: '642' },
  { fullName: 'Russian Federation', alpha2: 'RU', alpha3: 'RUS', unCode: '643' },
  { fullName: 'Rwanda', alpha2: 'RW', alpha3: 'RWA', unCode: '646' },

  // S
  { fullName: 'Saint - Barthélemy', alpha2: 'BL', alpha3: 'BLM', unCode: '652' },
  { fullName: 'Saint Helena', alpha2: 'SH', alpha3: 'SHN', unCode: '654' },
  { fullName: 'Saint Kitts and Nevis', alpha2: 'KN', alpha3: 'KNA', unCode: '659' },
  { fullName: 'Saint Lucia', alpha2: 'LC', alpha3: 'LCA', unCode: '662' },
  { fullName: 'Saint - Martin(French part)', alpha2: 'MF', alpha3: 'MAF', unCode: '663' },
  { fullName: 'Saint Pierre and Miquelon', alpha2: 'PM', alpha3: 'SPM', unCode: '666' },
  { fullName: 'Saint Vincent and Grenadines', alpha2: 'VC', alpha3: 'VCT', unCode: '670' },
  { fullName: 'Samoa', alpha2: 'WS', alpha3: 'WSM', unCode: '882' },
  { fullName: 'San Marino', alpha2: 'SM', alpha3: 'SMR', unCode: '674' },
  { fullName: 'Sao Tome and Principe', alpha2: 'ST', alpha3: 'STP', unCode: '678' },
  { fullName: 'Saudi Arabia', alpha2: 'SA', alpha3: 'SAU', unCode: '682' },
  { fullName: 'Senegal', alpha2: 'SN', alpha3: 'SEN', unCode: '686' },
  { fullName: 'Serbia', alpha2: 'RS', alpha3: 'SRB', unCode: '688' },
  { fullName: 'Seychelles', alpha2: 'SC', alpha3: 'SYC', unCode: '690' },
  { fullName: 'Sierra Leone', alpha2: 'SL', alpha3: 'SLE', unCode: '694' },
  { fullName: 'Singapore', alpha2: 'SG', alpha3: 'SGP', unCode: '702' },
  { fullName: 'Slovakia', alpha2: 'SK', alpha3: 'SVK', unCode: '703' },
  { fullName: 'Slovenia', alpha2: 'SI', alpha3: 'SVN', unCode: '705' },
  { fullName: 'Solomon Islands', alpha2: 'SB', alpha3: 'SLB', unCode: '090' },
  { fullName: 'Somalia', alpha2: 'SO', alpha3: 'SOM', unCode: '706' },
  { fullName: 'South Africa', alpha2: 'ZA', alpha3: 'ZAF', unCode: '710' },
  {
    fullName: 'South Georgia and the South Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
    unCode: '239',
  },
  { fullName: 'South Sudan', alpha2: 'SS', alpha3: 'SSD', unCode: '728' },
  { fullName: 'Spain', alpha2: 'ES', alpha3: 'ESP', unCode: '724' },
  { fullName: 'Sri Lanka', alpha2: 'LK', alpha3: 'LKA', unCode: '144' },
  { fullName: 'Sudan', alpha2: 'SD', alpha3: 'SDN', unCode: '736' },
  { fullName: 'Suriname', alpha2: 'SR', alpha3: 'SUR', unCode: '740' },
  { fullName: 'Svalbard and Jan Mayen Islands', alpha2: 'SJ', alpha3: 'SJM', unCode: '744' },
  { fullName: 'Swaziland', alpha2: 'SZ', alpha3: 'SWZ', unCode: '748' },
  { fullName: 'Sweden', alpha2: 'SE', alpha3: 'SWE', unCode: '752' },
  { fullName: 'Switzerland', alpha2: 'CH', alpha3: 'CHE', unCode: '756' },
  { fullName: 'Syrian Arab Republic(Syria)', alpha2: 'SY', alpha3: 'SYR', unCode: '760' },

  // T
  { fullName: 'Taiwan, Republic of China', alpha2: 'TW', alpha3: 'TWN', unCode: '158' },
  { fullName: 'Tajikistan', alpha2: 'TJ', alpha3: 'TJK', unCode: '762' },
  { fullName: 'Tanzania, United Republic of', alpha2: 'TZ', alpha3: 'TZA', unCode: '834' },
  { fullName: 'Thailand', alpha2: 'TH', alpha3: 'THA', unCode: '764' },
  { fullName: 'Timor - Leste', alpha2: 'TL', alpha3: 'TLS', unCode: '626' },
  { fullName: 'Togo', alpha2: 'TG', alpha3: 'TGO', unCode: '768' },
  { fullName: 'Tokelau', alpha2: 'TK', alpha3: 'TKL', unCode: '772' },
  { fullName: 'Tonga', alpha2: 'TO', alpha3: 'TON', unCode: '776' },
  { fullName: 'Trinidad and Tobago', alpha2: 'TT', alpha3: 'TTO', unCode: '780' },
  { fullName: 'Tunisia', alpha2: 'TN', alpha3: 'TUN', unCode: '788' },
  { fullName: 'Turkey', alpha2: 'TR', alpha3: 'TUR', unCode: '792' },
  { fullName: 'Turkmenistan', alpha2: 'TM', alpha3: 'TKM', unCode: '795' },
  { fullName: 'Turks and Caicos Islands', alpha2: 'TC', alpha3: 'TCA', unCode: '796' },
  { fullName: 'Tuvalu', alpha2: 'TV', alpha3: 'TUV', unCode: '798' },

  // U
  { fullName: 'Uganda', alpha2: 'UG', alpha3: 'UGA', unCode: '800' },
  { fullName: 'Ukraine', alpha2: 'UA', alpha3: 'UKR', unCode: '804' },
  { fullName: 'United Arab Emirates', alpha2: 'AE', alpha3: 'ARE', unCode: '784' },
  { fullName: 'United Kingdom', alpha2: 'GB', alpha3: 'GBR', unCode: '826' },
  { fullName: 'United States of America', alpha2: 'US', alpha3: 'USA', unCode: '840' },
  { fullName: 'US Minor Outlying Islands', alpha2: 'UM', alpha3: 'UMI', unCode: '581' },
  { fullName: 'Uruguay', alpha2: 'UY', alpha3: 'URY', unCode: '858' },
  { fullName: 'Uzbekistan', alpha2: 'UZ', alpha3: 'UZB', unCode: '860' },

  // V
  { fullName: 'Vanuatu', alpha2: 'VU', alpha3: 'VUT', unCode: '548' },
  { fullName: 'Venezuela(Bolivarian Republic)', alpha2: 'VE', alpha3: 'VEN', unCode: '862' },
  { fullName: 'Viet Nam', alpha2: 'VN', alpha3: 'VNM', unCode: '704' },
  { fullName: 'Virgin Islands, US', alpha2: 'VI', alpha3: 'VIR', unCode: '850' },

  // W
  { fullName: 'Wallis and Futuna Islands', alpha2: 'WF', alpha3: 'WLF', unCode: '876' },
  { fullName: 'Western Sahara', alpha2: 'EH', alpha3: 'ESH', unCode: '732' },

  // YZ
  { fullName: 'Yemen', alpha2: 'YE', alpha3: 'YEM', unCod: '887' },
  { fullName: 'Zambia', alpha2: 'ZM', alpha3: 'ZMB', unCod: '894' },
  { fullName: 'Zimbabwe', alpha2: 'ZW', alpha3: 'ZWE', unCod: '716' },
];

export default fullCountryInfo.map(({ alpha2, fullName }) => {
  return { key: alpha2, text: fullName };
});
